"""Report generation: structured markdown with SLA and contract info."""
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional


class ReportGenerator:
    """Generate cycle reports in markdown format."""

    def generate(
        self,
        task_id: str,
        subject: str,
        status: str,
        evidence: List[Dict[str, Any]],
        sla_violations: List[str],
        wall_clock_s: float,
        tool_calls: int,
        cycle_number: int = 1,
    ) -> str:
        """Produce structured markdown report."""
        lines = [
            "# Cycle Report",
            "",
            f"**Task:** {subject}",
            f"**Task ID:** {task_id}",
            f"**Cycle:** #{cycle_number}",
            f"**Status:** {status}",
            f"**Generated:** {datetime.now().isoformat()}",
            "",
            "## SLA",
            "",
            f"- Wall clock: {wall_clock_s:.1f}s",
            f"- Tool calls: {tool_calls}",
        ]

        if sla_violations:
            lines.extend([
                "",
                "### ⚠️ SLA Violations",
                "",
            ])
            for v in sla_violations:
                lines.append(f"- {v}")
        else:
            lines.append("- SLA: **COMPLIANT**")

        lines.extend([
            "",
            "## Evidence",
            "",
        ])

        if not evidence:
            lines.append("_No evidence recorded._")
        else:
            for i, ev in enumerate(evidence, 1):
                lines.extend([
                    f"### Gate {i}: {ev.get('gate_name', 'unknown')}",
                    "",
                    f"- **Command:** `{ev.get('command', 'N/A')}`",
                    f"- **Expected:** {ev.get('expected', 'N/A')}",
                    f"- **Actual:** {ev.get('actual', 'N/A')}",
                    f"- **Status:** {ev.get('status', 'N/A')}",
                    f"- **Duration:** {ev.get('duration_ms', 0):.0f}ms",
                    "",
                ])

        lines.extend([
            "---",
            "",
            "*Generated by fuzzybee v0.1.0*",
        ])

        return "\n".join(lines)
